### ISSUE TITLE
Mod causing the endgame stats to not show up

### ISSUE THREAD

**Issue by SkinlesSpartan** [Swaggies/BetterEXP#9] opened 2024-04-24 01:44 UTC
When I take off from a moon the endgame stats never show up, causing the game to not move forward to the next day.

**Comment by Swaggies** [comment] 2024-04-24 02:26
are you sure this is caused by BetterEXP? if so, please show me the error msg

**Comment by SkinlesSpartan** [comment] 2024-04-24 02:41
![Screenshot 2024-04-23 184009](https://github.com/Swaggies/BetterEXP/assets/140863744/a4f97c7d-e9b6-46d2-aadf-5a9593b9e21c)

**Comment by SkinlesSpartan** [comment] 2024-04-24 14:55
> ![Screenshot 2024-04-23 184009](https://private-user-images.githubusercontent.com/140863744/325056899-a4f97c7d-e9b6-46d2-aadf-5a9593b9e21c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzA3NTUsIm5iZiI6MTcxMzk3MDQ1NSwicGF0aCI6Ii8xNDA4NjM3NDQvMzI1MDU2ODk5LWE0Zjk3YzdkLWU5YjYtNDZkMi1hYWRmLTVhOTU5M2I5ZTIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNDU0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2Q0NmFjZTFhYjA0NDYyNTdkZjA4NjQxYzU0MWQ1ODQzNDQ2Mzk0MTFiNmY4NTY0NDlhOWNmMTViODM4ZWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QlGLhWJE7KWwGpfcCW9-tNdot8p2NleHhpK7rdWDQJE)

It only happens when I have BetterEXP installed

**Comment by Swaggies** [comment] 2024-04-26 20:19
what other mods did you have installed at the time? probably an issue with lobby expansion mods or LateCompany or a combination of the two, however this worked fine in my testing with MoreCompany.

**Comment by SkinlesSpartan** [comment] 2024-04-26 21:08
I don't have Late company installed, but I do have BiggerLobbies

**Comment by SkinlesSpartan** [comment] 2024-04-27 01:22
It would seem that this mod does not play nice with BiggerLobby

**Comment by Swaggies** [comment] 2024-04-27 01:27
i will attempt to see what goes on behind the scenes with BiggerLobby when i get the time but for now id recommend MoreCompany (esp if you want to use betterexp), thanks for the report tho

**Comment by SkinlesSpartan** [comment] 2024-04-27 02:32
I would, but MoreCompany doesn't work with another mod that I have, lol

No rush on you or anything though, just thought I would let you know

**Comment by Swaggies** [comment] 2024-07-25 20:26
closing since biggerlobby is deprecated now - feel free to create a new issue in case of other incompatibilities

**Closed by Swaggies** 2024-07-25 20:26 UTC
